server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://namdevaniket446:TOd09Wqu32PHamYn@cms.dtgydnp.mongodb.net/?retryWrites=true&w=majority&appName=cms
      database: Hook4Startup-dev
      auto-index-creation: true
  resources:
    static-locations: classpath:/static/
  rabbitmq:
    host: rabbit.lmq.cloudamqp.com
    port: 5672
    username: mmsfgliq
    password: l1nToIl0OyjRnfb2v_-aZNH9SJY2cMoe
    virtual-host: mmsfgliq
    listener:
      simple:
        prefetch: 1
        concurrency: 1
application:
  name: hook4startup

logging:
  level:
    org.springframework.security: DEBUG
